include/legacy_timescale.sv
+incdir+rtl/legacy
rtl/top/dma_axi64.sv
rtl/legacy/dma_axi64_apb_mux.v
rtl/legacy/dma_axi64_ch_reg_params.v
rtl/legacy/dma_axi64_core0.v
rtl/legacy/dma_axi64_core0_arbiter.v
rtl/legacy/dma_axi64_core0_axim_cmd.v
rtl/legacy/dma_axi64_core0_axim_rd.v
rtl/legacy/dma_axi64_core0_axim_rdata.v
rtl/legacy/dma_axi64_core0_axim_resp.v
rtl/legacy/dma_axi64_core0_axim_timeout.v
rtl/legacy/dma_axi64_core0_axim_wdata.v
rtl/legacy/dma_axi64_core0_axim_wr.v
rtl/legacy/dma_axi64_core0_ch.v
rtl/legacy/dma_axi64_core0_ch_calc.v
rtl/legacy/dma_axi64_core0_ch_calc_addr.v
rtl/legacy/dma_axi64_core0_ch_calc_joint.v
rtl/legacy/dma_axi64_core0_ch_calc_size.v
rtl/legacy/dma_axi64_core0_ch_empty.v
rtl/legacy/dma_axi64_core0_ch_fifo.v
rtl/legacy/dma_axi64_core0_ch_fifo_ctrl.v
rtl/legacy/dma_axi64_core0_ch_fifo_ptr.v
rtl/legacy/dma_axi64_core0_ch_offsets.v
rtl/legacy/dma_axi64_core0_ch_outs.v
rtl/legacy/dma_axi64_core0_ch_periph_mux.v
rtl/legacy/dma_axi64_core0_ch_rd_slicer.v
rtl/legacy/dma_axi64_core0_ch_reg.v
rtl/legacy/dma_axi64_core0_ch_reg_size.v
rtl/legacy/dma_axi64_core0_ch_remain.v
rtl/legacy/dma_axi64_core0_ch_wr_slicer.v
rtl/legacy/dma_axi64_core0_channels.v
rtl/legacy/dma_axi64_core0_channels_apb_mux.v
rtl/legacy/dma_axi64_core0_channels_mux.v
rtl/legacy/dma_axi64_core0_ctrl.v
rtl/legacy/dma_axi64_core0_top.v
rtl/legacy/dma_axi64_core0_wdt.v
rtl/legacy/dma_axi64_defines.v
rtl/legacy/dma_axi64_dual_core.v
rtl/legacy/dma_axi64_reg.v
rtl/legacy/dma_axi64_reg_core0.v
rtl/legacy/dma_axi64_reg_params.v
rtl/legacy/prgen_delay.v
rtl/legacy/prgen_demux8.v
rtl/legacy/prgen_fifo.v
rtl/legacy/prgen_joint_stall.v
rtl/legacy/prgen_min2.v
rtl/legacy/prgen_min3.v
rtl/legacy/prgen_mux8.v
rtl/legacy/prgen_or8.v
rtl/legacy/prgen_rawstat.v
rtl/legacy/prgen_scatter8_1.v
rtl/legacy/prgen_stall.v
rtl/legacy/prgen_swap_32.v
rtl/legacy/prgen_swap_64.v
tb/tb_dma_axi64.sv
